name: Update test stats

on:
  workflow_dispatch:
  schedule:
    - cron: 42 6-22/2 * * *

jobs:
  deploy:
    strategy:
      matrix:
        repo: [ 'tarantool/tarantool']
        branch: ['master', 'release/2.11', 'release/3.2', 'release/3.3', 'release/3.4']
    runs-on: ['self-hosted', 'multivac-crawler']
    env:
      LOG_STORAGE_BUCKET_URL: ${{ secrets.LOG_STORAGE_BUCKET_URL }}
      MULTIVAC_GITHUB_TOKEN: ${{ secrets.MULTIVAC_GITHUB_TOKEN }}
    steps:
      - name: update repo
        run: git checkout master && git fetch && git reset --hard origin/master
        working-directory: /mnt/storage/multivac

      - name: fetch.py for ${{ matrix.branch }}
        run: ./multivac/fetch.py --branch ${{ matrix.branch }} ${{ matrix.repo }}
        working-directory: /mnt/storage/multivac

      - name: Write data to InfluxDB
        env:
          INFLUX_JOB_BUCKET: ${{ secrets.INFLUX_JOB_BUCKET }}
          INFLUX_TEST_BUCKET: ${{ secrets.INFLUX_TEST_BUCKET }}
          INFLUX_TABLE_BUCKET: ${{ secrets.INFLUX_TABLE_BUCKET }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          ./multivac/gather_data.py -t --format influxdb --since 2d
        working-directory: /mnt/storage/multivac

      - name: Set the chat for failure notification
        if: failure()
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "CHAT_ID=${{ secrets.MYTEAM_SERVICE_CHAT_ID }}" >> "$GITHUB_ENV"
          else
              echo "CHAT_ID=${{ secrets.MYTEAM_DEBUG_CHAT_ID }}" >> "$GITHUB_ENV"
          fi

      - name: Send notification
        if: failure()
        uses: dasshit/myteam-notify@master
        with:
          api-url: ${{ secrets.MYTEAM_BOT_API }}
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          chat-id: ${{ env.CHAT_ID }}
          msg-text: "multivac failure:
                    https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
